# Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB, ComplementNB, GaussianNB
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report 
from sklearn import tree

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df_base = pd.read_csv(r'dataframes/baseline_dataframe.csv')
df_base.head()

state  converted_pledged_amount    goal_usd  backers_count  len_of_name  \
0      1                      1950   1000.0000             47           23   
1      1                     22404  15000.0000            271           51   
2      0                       165  12160.6569              3           34   
3      1                      2820   2800.0000              3           40   
4      1                      3725   3500.0000             35           31   

   len_of_description  creation_time_to_launch  planned_time  comics  crafts  \
0                 125               194.546111         720.0       0       0   
1                 108              5398.295000         720.0       0       0   
2                 133               129.195833        1439.0       0       0   
3                 121                98.460000         720.0       0       0   
4                 134              3824.832222         720.0       0       0   

   dance  design  fashion  film & video  food  games  journalism  music  \
0      0       0        0             0     0      1           0      0   
1      0       0        0             0     0      0           0      1   
2      0       0        0             0     0      1           0      0   
3      0       0        0             0     0      0           0      0   
4      0       0        0             0     0      0           0      1   

   photography  publishing  technology  theater  CAD  CHF  DKK  EUR  GBP  HKD  \
0            0           0           0        0    0    0    0    0    0    0   
1            0           0           0        0    0    0    0    0    0    0   
2            0           0           0        0    0    0    0    0    1    0   
3            0           1           0        0    0    0    0    0    0    0   
4            0           0           0        0    0    0    0    0    0    0   

   JPY  MXN  NOK  NZD  SEK  SGD  USD  AU  BE  CA  CH  DE  DK  ES  FR  GB  HK  \
0    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
1    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
2    0    0    0    0    0    0    0   0   0   0   0   0   0   0   0   1   0   
3    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
4    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   

   IE  IT  JP  LU  MX  NL  NO  NZ  SE  SG  US  Monday  Saturday  Sunday  \
0   0   0   0   0   0   0   0   0   0   0   1       0         0       0   
1   0   0   0   0   0   0   0   0   0   0   1       1         0       0   
2   0   0   0   0   0   0   0   0   0   0   0       0         0       0   
3   0   0   0   0   0   0   0   0   0   0   1       1         0       0   
4   0   0   0   0   0   0   0   0   0   0   1       0         0       0   

   Thursday  Tuesday  Wednesday  August  December  February  January  July  \
0         1        0          0       1         0         0        0     0   
1         0        0          0       0         0         0        0     0   
2         1        0          0       0         0         0        1     0   
3         0        0          0       0         1         0        0     0   
4         1        0          0       0         0         0        0     0   

   June  March  May  November  October  September  staff_pick  
0     0      0    0         0        0          0           0  
1     0      0    1         0        0          0           0  
2     0      0    0         0        0          0           0  
3     0      0    0         0        0          0           0  
4     0      0    0         0        0          0           0

In [4]:
df_new = df_base.drop(columns = ['converted_pledged_amount', 'backers_count'])

In [5]:
df_new.head()

state    goal_usd  len_of_name  len_of_description  \
0      1   1000.0000           23                 125   
1      1  15000.0000           51                 108   
2      0  12160.6569           34                 133   
3      1   2800.0000           40                 121   
4      1   3500.0000           31                 134   

   creation_time_to_launch  planned_time  comics  crafts  dance  design  \
0               194.546111         720.0       0       0      0       0   
1              5398.295000         720.0       0       0      0       0   
2               129.195833        1439.0       0       0      0       0   
3                98.460000         720.0       0       0      0       0   
4              3824.832222         720.0       0       0      0       0   

   fashion  film & video  food  games  journalism  music  photography  \
0        0             0     0      1           0      0            0   
1        0             0     0      0           0      1            0   
2        0             0     0      1           0      0            0   
3        0             0     0      0           0      0            0   
4        0             0     0      0           0      1            0   

   publishing  technology  theater  CAD  CHF  DKK  EUR  GBP  HKD  JPY  MXN  \
0           0           0        0    0    0    0    0    0    0    0    0   
1           0           0        0    0    0    0    0    0    0    0    0   
2           0           0        0    0    0    0    0    1    0    0    0   
3           1           0        0    0    0    0    0    0    0    0    0   
4           0           0        0    0    0    0    0    0    0    0    0   

   NOK  NZD  SEK  SGD  USD  AU  BE  CA  CH  DE  DK  ES  FR  GB  HK  IE  IT  \
0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
1    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
2    0    0    0    0    0   0   0   0   0   0   0   0   0   1   0   0   0   
3    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
4    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   

   JP  LU  MX  NL  NO  NZ  SE  SG  US  Monday  Saturday  Sunday  Thursday  \
0   0   0   0   0   0   0   0   0   1       0         0       0         1   
1   0   0   0   0   0   0   0   0   1       1         0       0         0   
2   0   0   0   0   0   0   0   0   0       0         0       0         1   
3   0   0   0   0   0   0   0   0   1       1         0       0         0   
4   0   0   0   0   0   0   0   0   1       0         0       0         1   

   Tuesday  Wednesday  August  December  February  January  July  June  March  \
0        0          0       1         0         0        0     0     0      0   
1        0          0       0         0         0        0     0     0      0   
2        0          0       0         0         0        1     0     0      0   
3        0          0       0         1         0        0     0     0      0   
4        0          0       0         0         0        0     0     0      0   

   May  November  October  September  staff_pick  
0    0         0        0          0           0  
1    1         0        0          0           0  
2    0         0        0          0           0  
3    0         0        0          0           0  
4    0         0        0          0           0

# Prepare dataset for modelling

In [6]:
### Devide dataset in X and y:
#X = df_base[['backers_count', 'len_of_name']]
X = df_new.iloc[:, 1:]
y = df_new.iloc[:, 0]
y

0         1
1         1
2         0
3         1
4         1
5         1
6         1
7         1
8         1
9         0
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        0
23        1
24        1
25        0
26        1
27        1
28        0
29        1
         ..
168947    1
168948    0
168949    0
168950    1
168951    0
168952    1
168953    0
168954    0
168955    0
168956    0
168957    1
168958    0
168959    0
168960    0
168961    1
168962    1
168963    0
168964    0
168965    0
168966    0
168967    1
168968    1
168969    0
168970    0
168971    0
168972    1
168973    1
168974    1
168975    1
168976    1
Name: state, Length: 168977, dtype: int64

In [7]:
### Scaling:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

scalerNB = MinMaxScaler()
X_scaled_NB = scalerNB.fit_transform(X)

In [8]:
### Train test split:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=41)

In [9]:
X_train_scaled,X_test_scaled,y_train,y_test = train_test_split(X_scaled,y,test_size=0.25,random_state=41)

In [10]:
X_train_scaled_NB ,X_test_scaled_NB ,y_train,y_test = train_test_split(X_scaled_NB,y,test_size=0.25,random_state=41)

In [11]:
test = pd.DataFrame(X_train_scaled)
test

0         1         2         3         4         5         6   \
0      -0.035192 -0.242267  0.271518 -0.298927 -0.192408  5.057378 -0.182524   
1      -0.034292  1.031303  0.614082 -0.348741  0.623496 -0.197731 -0.182524   
2      -0.036542 -0.624338 -0.147172 -0.365677 -0.225665 -0.197731 -0.182524   
3      -0.036401 -1.006409  0.766333 -0.351844 -0.225665 -0.197731 -0.182524   
4      -0.035192  0.012447  0.119267 -0.133040 -0.225665 -0.197731 -0.182524   
5      -0.035642 -0.560659 -0.185235 -0.365861 -0.225665 -0.197731  5.478717   
6      -0.033842 -0.751695  0.614082 -0.038342 -0.991122 -0.197731 -0.182524   
7       0.059958  1.094982  0.043141 -0.353470 -0.225665 -0.197731 -0.182524   
8      -0.035192 -0.051231 -2.468998 -0.160290 -1.570472 -0.197731 -0.182524   
9      -0.020655  0.521875  0.614082  0.109452  0.184949 -0.197731 -0.182524   
10     -0.024116  0.840268  0.576019  0.638058 -0.225665 -0.197731 -0.182524   
11     -0.023491 -0.624338  0.842458 -0.271866  2.329402 -0.197731 -0.182524   
12     -0.015758 -0.942730  0.728270 -0.036923 -0.225665 -0.197731 -0.182524   
13     -0.030241  1.094982  0.842458 -0.062199 -0.225665 -0.197731 -0.182524   
14     -0.026191 -0.051231  0.385706 -0.212225  2.325859 -0.197731 -0.182524   
15     -0.014489 -1.324801  0.804396  0.238576 -0.225665 -0.197731 -0.182524   
16     -0.009989  1.286017  0.804396 -0.289077  2.254808 -0.197731 -0.182524   
17     -0.035417  0.840268 -0.794238 -0.256122  1.235551 -0.197731 -0.182524   
18     -0.027651 -0.624338 -1.936120  0.041852 -0.278792 -0.197731 -0.182524   
19     -0.032492  0.521875  0.842458 -0.154688 -0.220276 -0.197731 -0.182524   
20     -0.035447  0.394518  0.804396 -0.020477  0.226920 -0.197731 -0.182524   
21     -0.035912  2.559587  1.375336 -0.306714 -0.222121 -0.197731 -0.182524   
22     -0.036045  1.413374  0.233455 -0.326778 -0.216240 -0.197731 -0.182524   
23     -0.036002 -0.560659  0.005079  2.179076 -0.395766 -0.197731 -0.182524   
24     -0.036767 -1.452158  0.385706 -0.278219 -0.225665 -0.197731 -0.182524   
25     -0.031592 -1.452158 -0.299423 -0.365673 -0.230034  5.057378 -0.182524   
26     -0.036982  0.394518 -3.078001  1.976062 -0.225665 -0.197731 -0.182524   
27     -0.033538  1.094982  0.652145 -0.359152  2.325859 -0.197731 -0.182524   
28     -0.020467  1.604410  0.842458 -0.217701 -0.272430 -0.197731 -0.182524   
29     -0.022778  1.286017  0.005079 -0.081532 -0.225665 -0.197731 -0.182524   
...          ...       ...       ...       ...       ...       ...       ...   
126702 -0.036317 -0.688016  0.766333 -0.354512 -0.991122  5.057378 -0.182524   
126703 -0.036086  0.203483  0.347643 -0.349775 -0.991122 -0.197731 -0.182524   
126704 -0.035192 -1.643194 -2.468998 -0.297481  0.392274 -0.197731 -0.182524   
126705 -0.027991  1.604410  0.842458  0.107629 -0.225665 -0.197731 -0.182524   
126706 -0.036542 -1.515837 -0.032984 -0.352716  1.462624 -0.197731 -0.182524   
126707 -0.014489 -0.688016  0.423768  2.212388 -0.225665 -0.197731 -0.182524   
126708 -0.036542  1.158660  0.309580 -0.327460 -0.225665 -0.197731 -0.182524   
126709 -0.018990 -1.515837 -1.327116  0.299373 -0.225665 -0.197731 -0.182524   
126710  0.120740  0.712911  0.461831 -0.201499 -0.225665 -0.197731 -0.182524   
126711 -0.020354  0.139804 -0.946489 -0.259992  0.049850 -0.197731 -0.182524   
126712 -0.036092 -0.815373  0.842458 -0.349685 -0.225665 -0.197731 -0.182524   
126713 -0.009989  0.076126 -1.517430 -0.355452 -0.225665 -0.197731 -0.182524   
126714 -0.034922 -0.305945  0.157329 -0.293769  2.322315 -0.197731 -0.182524   
126715 -0.032992  1.413374 -1.517430 -0.295553 -0.225665 -0.197731 -0.182524   
126716 -0.021690 -0.178588  0.614082 -0.299403 -0.225665 -0.197731 -0.182524   
126717 -0.036870 -1.006409 -0.718113 -0.351546 -2.436985 -0.197731 -0.182524   
126718  0.053020 -0.815373 -0.223298 -0.139602  2.329402 -0.197731 -0.182524   
126719  0.008014 -1.770551  0.614082 -0.351570  1.307183 -0.197731 -0.182524   
126720 -0.0269

## Logistic Regression

In [12]:
logistic_regression= LogisticRegression()
logistic_regression.fit(X_train_scaled,y_train)
y_pred=logistic_regression.predict(X_test_scaled)

In [13]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.7058586815007694


In [14]:
confusion_matrix(y_test, y_pred)

array([[10513,  8037],
       [ 4389, 19306]])

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.57      0.63     18550
           1       0.71      0.81      0.76     23695

    accuracy                           0.71     42245
   macro avg       0.71      0.69      0.69     42245
weighted avg       0.71      0.71      0.70     42245



## Decision Tree

In [16]:
decision_tree = tree.DecisionTreeClassifier(max_depth = 10, random_state = 41)
decision_tree.fit(X_train_scaled,y_train)
y_pred = decision_tree.predict(X_test_scaled)

In [17]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.7204166173511658


In [18]:
confusion_matrix(y_test, y_pred)

array([[10041,  8509],
       [ 3302, 20393]])

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.54      0.63     18550
           1       0.71      0.86      0.78     23695

    accuracy                           0.72     42245
   macro avg       0.73      0.70      0.70     42245
weighted avg       0.73      0.72      0.71     42245



## KNN

In [20]:
###1. without scaling

In [21]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
knn.fit(X_train, np.ravel(y_train))
y_pred = knn.predict(X_test)

In [22]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.6411172919872175


In [23]:
confusion_matrix(y_test, y_pred)

array([[ 9887,  8663],
       [ 6498, 17197]])

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.53      0.57     18550
           1       0.67      0.73      0.69     23695

    accuracy                           0.64     42245
   macro avg       0.63      0.63      0.63     42245
weighted avg       0.64      0.64      0.64     42245



In [25]:
###2. with scaling
############################## DONT' TOUCH SINCE VERY COMPUTATIONAL EXPENSIVE

In [26]:
#knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean', n_jobs=-1)
#knn.fit(X_train_scaled, np.ravel(y_train))
#y_pred = knn.predict(X_test_scaled)

In [27]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.6411172919872175


In [28]:
confusion_matrix(y_test, y_pred)

array([[ 9887,  8663],
       [ 6498, 17197]])

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.53      0.57     18550
           1       0.67      0.73      0.69     23695

    accuracy                           0.64     42245
   macro avg       0.63      0.63      0.63     42245
weighted avg       0.64      0.64      0.64     42245



## Naive Bayes

In [30]:
##1st no scaling:

In [31]:
BernoulliNB, ComplementNB, GaussianNB

(sklearn.naive_bayes.BernoulliNB,
 sklearn.naive_bayes.ComplementNB,
 sklearn.naive_bayes.GaussianNB)

In [32]:
bernoullinb = BernoulliNB().fit(X_train, y_train)
complementnb = ComplementNB().fit(X_train, y_train)
gaussiannb = GaussianNB().fit(X_train, y_train)

In [33]:
bernoullinb.score(X_test, y_test)

0.6614510592969582

In [34]:
complementnb.score(X_test, y_test)

0.6310569298141792

In [35]:
gaussiannb.score(X_test, y_test)

0.5851343354243106

In [36]:
## with scaling:

In [37]:
bernoullinb = BernoulliNB().fit(X_train_scaled_NB, y_train)
complementnb = ComplementNB().fit(X_train_scaled_NB, y_train)
gaussiannb = GaussianNB().fit(X_train_scaled_NB, y_train)

In [38]:
bernoullinb.score(X_test_scaled_NB, y_test)

0.6614984021777726

In [39]:
complementnb.score(X_test_scaled_NB, y_test)

0.6646467037519233

In [40]:
gaussiannb.score(X_test_scaled_NB, y_test)

0.6431767073026393

## Ridge

In [41]:
# without scaling
clf = RidgeClassifier().fit(X_train, y_train)
print("test_score: ",(clf.score(X_test, y_test)))
print("train_score: ",(clf.score(X_train, y_train)))

test_score:  0.6871582435791218
train_score:  0.6862907552946375


/Users/fabianwerkmeister/opt/anaconda3/envs/nf/lib/python3.6/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=4.43906e-18): result may not be accurate.
  overwrite_a=True).T


In [42]:
# with scaling
clf = RidgeClassifier().fit(X_train_scaled, y_train)
print("test_score: ",(clf.score(X_test_scaled, y_test)))
print("train_score: ",(clf.score(X_train_scaled, y_train)))

test_score:  0.6871582435791218
train_score:  0.6862986459615567


## Lasso

In [43]:
# default no scaling
lasso = Lasso()
lasso.fit(X_train,y_train)
train_score=lasso.score(X_train,y_train)
test_score=lasso.score(X_test,y_test)
coeff_used = np.sum(lasso.coef_!=0)
print ("training score:", train_score) 
print ("test score: ", test_score)
print ("number of features used: ", coeff_used)

training score: 0.025187876307243173
test score:  0.024355101783822386
number of features used:  3


In [44]:
# default with scaling

lasso = Lasso()
lasso.fit(X_train_scaled,y_train)
train_score=lasso.score(X_train_scaled,y_train)
test_score=lasso.score(X_test_scaled,y_test)
coeff_used = np.sum(lasso.coef_!=0)
print ("training score:", train_score) 
print ("test score: ", test_score)
print ("number of features used: ", coeff_used)

training score: 0.0
test score:  -1.1781908781927086e-10
number of features used:  0


In [45]:
# lasso with alpha 0,001 and no scaling

lasso = Lasso(alpha=0.001, max_iter=10e5)
lasso.fit(X_train,y_train)
train_score=lasso.score(X_train,y_train)
test_score=lasso.score(X_test,y_test)
coeff_used = np.sum(lasso.coef_!=0)
print ("training score:", train_score) 
print ("test score: ", test_score)
print ("number of features used: ", coeff_used)

training score: 0.1739826769792986
test score:  0.17490457520705172
number of features used:  35


In [46]:
# lasso with alpha 0,001 and scaling

lasso = Lasso(alpha=0.001, max_iter=10e5)
lasso.fit(X_train_scaled,y_train)
train_score=lasso.score(X_train_scaled,y_train)
test_score=lasso.score(X_test_scaled,y_test)
coeff_used = np.sum(lasso.coef_!=0)
print ("training score:", train_score) 
print ("test score: ", test_score)
print ("number of features used: ", coeff_used)

training score: 0.177515053026529
test score:  0.1784424158061273
number of features used:  54


## Random Forest

In [47]:
# no scaling
rnc = RandomForestClassifier(n_estimators=100, 
                               random_state=42, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1)

rnc.fit(X_train, y_train)
y_pred = rnc.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    6.2s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   12.9s finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s


Accuracy:  0.7408450704225352
              precision    recall  f1-score   support

           0       0.73      0.64      0.69     18550
           1       0.75      0.82      0.78     23695

    accuracy                           0.74     42245
   macro avg       0.74      0.73      0.73     42245
weighted avg       0.74      0.74      0.74     42245

[[11935  6615]
 [ 4333 19362]]


[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.5s finished


In [48]:
# with scaling
rnc = RandomForestClassifier(n_estimators=100, 
                               random_state=42, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1)
rnc.fit(X_train_scaled, y_train)
y_pred = rnc.predict(X_test_scaled)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   10.1s finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.3s


Accuracy:  0.7413658421114925
              precision    recall  f1-score   support

           0       0.73      0.64      0.69     18550
           1       0.75      0.82      0.78     23695

    accuracy                           0.74     42245
   macro avg       0.74      0.73      0.73     42245
weighted avg       0.74      0.74      0.74     42245

[[11938  6612]
 [ 4314 19381]]


[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.7s finished


## AdaBoost

In [49]:
# without scaling
#abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
abc = AdaBoostClassifier(n_estimators=50, learning_rate=1, random_state=42)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy:  0.7368919398745414
              precision    recall  f1-score   support

           0       0.72      0.65      0.68     18550
           1       0.75      0.81      0.77     23695

    accuracy                           0.74     42245
   macro avg       0.73      0.73      0.73     42245
weighted avg       0.74      0.74      0.73     42245

[[12049  6501]
 [ 4614 19081]]


## Gradiend Descent Boost

In [50]:
gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=1, max_features=2, 
                                        max_depth=2, random_state=0)
gb_clf.fit(X_train, y_train)
y_pred = gb_clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy:  0.6797964256124985
              precision    recall  f1-score   support

           0       0.66      0.55      0.60     18550
           1       0.69      0.78      0.73     23695

    accuracy                           0.68     42245
   macro avg       0.68      0.67      0.67     42245
weighted avg       0.68      0.68      0.68     42245

[[10283  8267]
 [ 5260 18435]]


## XGBoost

In [52]:
xgb_clf = XGBClassifier(random_state=42)
xgb_clf.fit(X_train, y_train)
score = xgb_clf.score(X_test, y_test)
print(score)
y_pred = xgb_clf.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.7437803290330217
Accuracy:  0.7437803290330217
              precision    recall  f1-score   support

           0       0.75      0.62      0.68     18550
           1       0.74      0.84      0.79     23695

    accuracy                           0.74     42245
   macro avg       0.75      0.73      0.73     42245
weighted avg       0.75      0.74      0.74     42245

[[11448  7102]
 [ 3722 19973]]
