# Setup

In [27]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB, ComplementNB, GaussianNB

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report 
from sklearn import tree

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
df_base = pd.read_csv(r'dataframes/baseline_dataframe.csv')
df_base.head()

state  converted_pledged_amount    goal_usd  backers_count  len_of_name  \
0      1                      1950   1000.0000             47           23   
1      1                     22404  15000.0000            271           51   
2      0                       165  12160.6569              3           34   
3      1                      2820   2800.0000              3           40   
4      1                      3725   3500.0000             35           31   

   len_of_description  creation_time_to_launch  planned_time  comics  crafts  \
0                 125               194.546111         720.0       0       0   
1                 108              5398.295000         720.0       0       0   
2                 133               129.195833        1439.0       0       0   
3                 121                98.460000         720.0       0       0   
4                 134              3824.832222         720.0       0       0   

   dance  design  fashion  film & video  food  games  journalism  music  \
0      0       0        0             0     0      1           0      0   
1      0       0        0             0     0      0           0      1   
2      0       0        0             0     0      1           0      0   
3      0       0        0             0     0      0           0      0   
4      0       0        0             0     0      0           0      1   

   photography  publishing  technology  theater  CAD  CHF  DKK  EUR  GBP  HKD  \
0            0           0           0        0    0    0    0    0    0    0   
1            0           0           0        0    0    0    0    0    0    0   
2            0           0           0        0    0    0    0    0    1    0   
3            0           1           0        0    0    0    0    0    0    0   
4            0           0           0        0    0    0    0    0    0    0   

   JPY  MXN  NOK  NZD  SEK  SGD  USD  AU  BE  CA  CH  DE  DK  ES  FR  GB  HK  \
0    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
1    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
2    0    0    0    0    0    0    0   0   0   0   0   0   0   0   0   1   0   
3    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   
4    0    0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   

   IE  IT  JP  LU  MX  NL  NO  NZ  SE  SG  US  Monday  Saturday  Sunday  \
0   0   0   0   0   0   0   0   0   0   0   1       0         0       0   
1   0   0   0   0   0   0   0   0   0   0   1       1         0       0   
2   0   0   0   0   0   0   0   0   0   0   0       0         0       0   
3   0   0   0   0   0   0   0   0   0   0   1       1         0       0   
4   0   0   0   0   0   0   0   0   0   0   1       0         0       0   

   Thursday  Tuesday  Wednesday  August  December  February  January  July  \
0         1        0          0       1         0         0        0     0   
1         0        0          0       0         0         0        0     0   
2         1        0          0       0         0         0        1     0   
3         0        0          0       0         1         0        0     0   
4         1        0          0       0         0         0        0     0   

   June  March  May  November  October  September  staff_pick  
0     0      0    0         0        0          0           0  
1     0      0    1         0        0          0           0  
2     0      0    0         0        0          0           0  
3     0      0    0         0        0          0           0  
4     0      0    0         0        0          0           0

In [8]:
df_new = df_base.drop(columns = ['converted_pledged_amount', 'backers_count'])

In [9]:
df_new.head()

state    goal_usd  len_of_name  len_of_description  \
0      1   1000.0000           23                 125   
1      1  15000.0000           51                 108   
2      0  12160.6569           34                 133   
3      1   2800.0000           40                 121   
4      1   3500.0000           31                 134   

   creation_time_to_launch  planned_time  comics  crafts  dance  design  \
0               194.546111         720.0       0       0      0       0   
1              5398.295000         720.0       0       0      0       0   
2               129.195833        1439.0       0       0      0       0   
3                98.460000         720.0       0       0      0       0   
4              3824.832222         720.0       0       0      0       0   

   fashion  film & video  food  games  journalism  music  photography  \
0        0             0     0      1           0      0            0   
1        0             0     0      0           0      1            0   
2        0             0     0      1           0      0            0   
3        0             0     0      0           0      0            0   
4        0             0     0      0           0      1            0   

   publishing  technology  theater  CAD  CHF  DKK  EUR  GBP  HKD  JPY  MXN  \
0           0           0        0    0    0    0    0    0    0    0    0   
1           0           0        0    0    0    0    0    0    0    0    0   
2           0           0        0    0    0    0    0    1    0    0    0   
3           1           0        0    0    0    0    0    0    0    0    0   
4           0           0        0    0    0    0    0    0    0    0    0   

   NOK  NZD  SEK  SGD  USD  AU  BE  CA  CH  DE  DK  ES  FR  GB  HK  IE  IT  \
0    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
1    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
2    0    0    0    0    0   0   0   0   0   0   0   0   0   1   0   0   0   
3    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   
4    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   0   0   

   JP  LU  MX  NL  NO  NZ  SE  SG  US  Monday  Saturday  Sunday  Thursday  \
0   0   0   0   0   0   0   0   0   1       0         0       0         1   
1   0   0   0   0   0   0   0   0   1       1         0       0         0   
2   0   0   0   0   0   0   0   0   0       0         0       0         1   
3   0   0   0   0   0   0   0   0   1       1         0       0         0   
4   0   0   0   0   0   0   0   0   1       0         0       0         1   

   Tuesday  Wednesday  August  December  February  January  July  June  March  \
0        0          0       1         0         0        0     0     0      0   
1        0          0       0         0         0        0     0     0      0   
2        0          0       0         0         0        1     0     0      0   
3        0          0       0         1         0        0     0     0      0   
4        0          0       0         0         0        0     0     0      0   

   May  November  October  September  staff_pick  
0    0         0        0          0           0  
1    1         0        0          0           0  
2    0         0        0          0           0  
3    0         0        0          0           0  
4    0         0        0          0           0

# Prepare dataset for modelling

In [10]:
### Devide dataset in X and y:
#X = df_base[['backers_count', 'len_of_name']]
X = df_new.iloc[:, 1:]
y = df_new.iloc[:, 0]
y

0         1
1         1
2         0
3         1
4         1
         ..
168972    1
168973    1
168974    1
168975    1
168976    1
Name: state, Length: 168977, dtype: int64

In [11]:
### Scaling:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
### Train test split:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=41)

In [13]:
X_train_scaled,X_test_scaled,y_train,y_test = train_test_split(X_scaled,y,test_size=0.25,random_state=41)

## Logistic Regression

In [14]:
logistic_regression= LogisticRegression()
logistic_regression.fit(X_train_scaled,y_train)
y_pred=logistic_regression.predict(X_test_scaled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.7058350100603622


In [16]:
confusion_matrix(y_test, y_pred)

array([[10512,  8038],
       [ 4389, 19306]])

In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.57      0.63     18550
           1       0.71      0.81      0.76     23695

    accuracy                           0.71     42245
   macro avg       0.71      0.69      0.69     42245
weighted avg       0.71      0.71      0.70     42245



## Decision Tree

In [18]:
decision_tree = tree.DecisionTreeClassifier(max_depth = 10, random_state = 41)
decision_tree.fit(X_train_scaled,y_train)
y_pred = decision_tree.predict(X_test_scaled)

In [19]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.7204166173511658


In [20]:
confusion_matrix(y_test, y_pred)

array([[10041,  8509],
       [ 3302, 20393]])

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.54      0.63     18550
           1       0.71      0.86      0.78     23695

    accuracy                           0.72     42245
   macro avg       0.73      0.70      0.70     42245
weighted avg       0.73      0.72      0.71     42245



## KNN

In [18]:
###1. without scaling

In [19]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
knn.fit(X_train, np.ravel(y_train))
y_pred = knn.predict(X_test)

In [20]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.6411172919872175


In [21]:
confusion_matrix(y_test, y_pred)

array([[ 9887,  8663],
       [ 6498, 17197]])

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.53      0.57     18550
           1       0.67      0.73      0.69     23695

    accuracy                           0.64     42245
   macro avg       0.63      0.63      0.63     42245
weighted avg       0.64      0.64      0.64     42245



In [24]:
###2. with scaling

In [22]:
#knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean', n_jobs=-1)
#knn.fit(X_train_scaled, np.ravel(y_train))
#y_pred = knn.predict(X_test_scaled)

In [23]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.6428926500177535


In [24]:
confusion_matrix(y_test, y_pred)

array([[10500,  8050],
       [ 7036, 16659]])

In [ ]:
print(classification_report(y_test, y_pred))

## Naive Bayse

In [ ]:
##1st no scaling:

In [ ]:
BernoulliNB, ComplementNB, GaussianNB

In [28]:
bernoullinb = BernoulliNB().fit(X_train, y_train)
complementnb = ComplementNB().fit(X_train, y_train)
gaussiannb = GaussianNB().fit(X_train, y_train)

In [29]:
bernoullinb.score(X_test, y_test)

0.6614510592969582

In [30]:
complementnb.score(X_test, y_test)

0.6310569298141792

In [32]:
gaussiannb.score(X_test, y_test)

0.5851343354243106